// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients_create.sql

package db

import (
	"context"
	"database/sql"
)

const addClient = `-- name: AddClient :one
INSERT INTO clients (name, email, join_code, logo_url) VALUES ($1, $2, $3, $4) RETURNING id, name, email, join_code, logo_url, created_at, updated_at
`

type AddClientParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	JoinCode string         `json:"join_code"`
	LogoUrl  sql.NullString `json:"logo_url"`
}

func (q *Queries) AddClient(ctx context.Context, arg AddClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, addClient,
		arg.Name,
		arg.Email,
		arg.JoinCode,
		arg.LogoUrl,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.JoinCode,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
