// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const addClient = `-- name: AddClient :one
INSERT INTO clients (name, email, join_code, logo_url) VALUES ($1, $2, $3, $4) RETURNING id, name, email, join_code, logo_url, created_at, updated_at
`

type AddClientParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	JoinCode string         `json:"join_code"`
	LogoUrl  sql.NullString `json:"logo_url"`
}

func (q *Queries) AddClient(ctx context.Context, arg AddClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, addClient,
		arg.Name,
		arg.Email,
		arg.JoinCode,
		arg.LogoUrl,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.JoinCode,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1 RETURNING name
`

func (q *Queries) DeleteClient(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClients = `-- name: GetClients :many
SELECT id, name, email, join_code, logo_url, created_at, updated_at FROM clients
`

func (q *Queries) GetClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.JoinCode,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET name = $2, email = $3, logo_url = $4, updated_at = NOW() 
WHERE id = $1 
RETURNING id, name, email, join_code, logo_url, created_at, updated_at
`

type UpdateClientParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	LogoUrl sql.NullString `json:"logo_url"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.LogoUrl,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.JoinCode,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
