// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients_update.sql

package db

import (
	"context"
	"database/sql"
)

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET name = $2, email = $3, logo_url = $4, updated_at = NOW() 
WHERE id = $1 
RETURNING id, name, email, join_code, logo_url, created_at, updated_at
`

type UpdateClientParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	LogoUrl sql.NullString `json:"logo_url"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.LogoUrl,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.JoinCode,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
