// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	JoinCode  string         `json:"join_code"`
	LogoUrl   sql.NullString `json:"logo_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}

type User struct {
	ID        int32         `json:"id"`
	ClientID  sql.NullInt32 `json:"client_id"`
	RoleID    sql.NullInt32 `json:"role_id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	LastLogin sql.NullTime  `json:"last_login"`
}
