// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddClient(ctx context.Context, arg AddClientParams) (Client, error)
	GetClients(ctx context.Context) ([]Client, error)
}

var _ Querier = (*Queries)(nil)
