// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (client_id, role_id, name, email, password) VALUES ($1, $2, $3, $4, $5) RETURNING id, client_id, role_id, name, email, password, created_at, updated_at, last_login
`

type AddUserParams struct {
	ClientID sql.NullInt32 `json:"client_id"`
	RoleID   sql.NullInt32 `json:"role_id"`
	Name     string        `json:"name"`
	Email    string        `json:"email"`
	Password string        `json:"password"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.ClientID,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING name
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUsersByClientID = `-- name: GetUsersByClientID :many
SELECT u.name, u.email, c.name FROM users u
JOIN clients c ON u.client_id = c.id
WHERE client_id = $1
`

type GetUsersByClientIDRow struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) GetUsersByClientID(ctx context.Context, clientID sql.NullInt32) ([]GetUsersByClientIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByClientIDRow
	for rows.Next() {
		var i GetUsersByClientIDRow
		if err := rows.Scan(&i.Name, &i.Email, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
